apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  selector:
    matchLabels:
      app: db
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: quay.io/aminrf/mysql:5.7.16
        name: db
        env:
          - name: "MYSQL_ROOT_PASSWORD"
            value: "ghazal1234rasta1234"
            # valueFrom: #"ghazal1234rasta1234"
            #   secretKeyRef:
            #     name: mysql-root-pass
            #     key: password
          - name: "MYSQL_DATABASE"
            value: "BolbolestanDB"
            # valueFrom: #"BolbolestanDB"
            #   secretKeyRef:
            #     name: mysql-database
            #     key: database
        ports:
        - containerPort: 3306
          name: db
        resources:
            limits:
              memory: "500M"
              cpu: "333m"
            requests:
              memory: "500M"
              cpu: "333m"
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
          subPath: backend-mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc